# Header
menu:
  Home: /
  Home2: http://www.tumogu.cn
  AiLiao: http://www.tumogu.cn:3000
  Mushroom UI: /mr
  Github: https://github.com/renhongl
  Codepen: https://codepen.io/renhongl
  Archives: /archives
  
  

# Content
excerpt_link: More
prev: Pre
next: Next
# reply: Comment
# share: Share
fancybox: true

# Sidebar
widgets:
- search
- music
- about
- support
- category
- recent_posts
- tag
- tagcloud
- link
# - gate
# - account

# Miscellaneous
google_analytics:
# duoshuo_shortname: 
disqus_shortname: renhongl
rss: 
google_site_verification: 
baidu_site_verification: 
favicon: 
music: http://other.web.rc01.sycdn.kuwo.cn/resource/n3/99/21/1172239707.mp3